#!/usr/bin/env python3
"""Bake an anti-aliased ASCII font.

Writes:
  src/font_aa.bin         — packed alpha bitmaps (concatenated glyph bboxes)
  src/font_aa_metrics.h   — glyph metric table

Run once from the project root.  Commit the outputs.
"""
import os
from PIL import Image, ImageDraw, ImageFont

PX_HEIGHT = 40          # source font pixel height (target_h = scale * 8)
CELL_W    = 48          # generous; bbox cropping will shrink it
CELL_H    = 56

FONT_CANDIDATES = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
    "/usr/share/fonts/truetype/freefont/FreeSansBold.ttf",
    "/usr/share/fonts/truetype/ubuntu/Ubuntu-B.ttf",
    "/usr/share/fonts/truetype/ubuntu/Ubuntu-R.ttf",
    "/usr/share/fonts/TTF/DejaVuSans-Bold.ttf",     # Arch
    "/System/Library/Fonts/Helvetica.ttc",          # macOS
    "/Library/Fonts/Arial.ttf",                     # macOS
]

def find_font():
    for p in FONT_CANDIDATES:
        if os.path.exists(p):
            return p
    for root in ["/usr/share/fonts", "/usr/local/share/fonts"]:
        if not os.path.isdir(root):
            continue
        for dirpath, _, files in os.walk(root):
            for fn in files:
                if fn.lower().endswith((".ttf", ".otf")):
                    return os.path.join(dirpath, fn)
    raise RuntimeError("No TTF font found")

def bake():
    font_path = find_font()
    print(f"Baking font from {font_path}")
    font = ImageFont.truetype(font_path, PX_HEIGHT)

    bitmap  = bytearray()
    metrics = []

    for code in range(32, 128):
        ch  = chr(code)
        img = Image.new("L", (CELL_W, CELL_H), 0)
        draw = ImageDraw.Draw(img)
        try:
            draw.text((0, 0), ch, fill=255, font=font, anchor="lt")
        except TypeError:
            draw.text((0, 0), ch, fill=255, font=font)

        bbox = img.getbbox()
        if bbox is None:
            # blank glyph (space)
            metrics.append((0, 0, 0, 0, PX_HEIGHT // 2))
            continue

        min_x, min_y, max_x, max_y = bbox
        gw = max_x - min_x
        gh = max_y - min_y

        pixels = img.load()
        for py in range(min_y, max_y):
            for px in range(min_x, max_x):
                bitmap.append(pixels[px, py])

        try:
            adv = int(round(font.getlength(ch)))
        except AttributeError:
            adv = max_x - min_x
        if adv < 1:   adv = 1
        if adv > 255: adv = 255

        metrics.append((min_x, min_y, gw, gh, adv))

    os.makedirs("src", exist_ok=True)
    with open("src/font_aa.bin", "wb") as f:
        f.write(bitmap)

    with open("src/font_aa_metrics.h", "w") as f:
        f.write("/* Auto-generated by tools/bake_font.py - do not edit. */\n")
        f.write("#ifndef FONT_AA_METRICS_H\n#define FONT_AA_METRICS_H\n\n")
        f.write('#include "core.h"\n\n')
        f.write(f"#define FONT_AA_PX_HEIGHT {PX_HEIGHT}\n\n")
        f.write("struct font_aa_glyph { s16 bx, by; u16 w, h, adv; };\n\n")
        f.write("static const struct font_aa_glyph font_aa_metrics[96] = {\n")
        for m in metrics:
            f.write(f"    {{{m[0]}, {m[1]}, {m[2]}, {m[3]}, {m[4]}}},\n")
        f.write("};\n\n#endif\n")

    print(f"Wrote src/font_aa.bin ({len(bitmap)} bytes)")
    print(f"Wrote src/font_aa_metrics.h ({len(metrics)} glyphs)")

if __name__ == "__main__":
    bake()
